### PR TITLE
Update cluster lifecycle repositories to include new repositories in the kubernetes-sigs organization

### PR DESCRIPTION
**Pull request by roberthbailey**
I've updated the repository groups for cluster lifecycle to better reflect the subprojects for the SIG as described in https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
LGTM, merging.

**Comment by roberthbailey** [comment]
Does this "go live" automatically? Or do I need to wait for some sort of push to happen?

**Comment by lukaszgryglicki** [comment]
After the PR is merged, I'm applying this on the server, so the new data is using the new repository groups definition.

**Pull request merged**
