### PR TITLE
Adding racher labs to the list of acquisitions

### PR DESCRIPTION
**Pull request by mattfarina**
This was suggested over in https://github.com/cncf/gitdm/pull/536

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Thanks, will merge tomorrow (and update data) - just make sure the name is correct: `SUSE` vs. `SuSE`.

**Comment by lukaszgryglicki** [comment]
I'll wait for the [final feeback](https://github.com/cncf/gitdm/pull/536#issuecomment-741519599).

**Comment by lukaszgryglicki** [comment]
Hi, we decided to keep the old company name, so I'll merge the cncf/gitdm PR instead. Thanks for this PR.

**Comment by mattfarina** [comment]
@lukaszgryglicki I chased this down with management. We want to merge the data as Deis/Microsoft and Bitnami/VMware have done.

**Comment by caniszczyk** [comment]
fine with us, we can merge this in @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Hmm, I've already merged a version with an end date, so I've replaced all `Rancher Labs` with `Rancher Labs < 2020-12-01, SUSE`.

**Comment by mattfarina** [comment]
@lukaszgryglicki The change got merged while I was going through management to see what they wanted. They would like to follow the Deis/Microsoft and Bitnami/VMware route and have SUSE to  subsume Rancher Labs past stats. Is that still possible?

**Comment by lukaszgryglicki** [comment]
Yes, I'll just merge this PR.

**Comment by mattfarina** [comment]
Thanks @lukaszgryglicki

**Pull request merged**
