### PR TITLE
Add knative & knative-sandbox repo_groups

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
- Allow filtering https://knative.teststats.cncf.io stats by filtering
  using the github orgs

Signed-off-by: Sameer Vohra <vsameer@vmware.com>

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Merged, will regenerate Knative data to reflect those changes after I merge a few other cncf/gitdm PRs.

**Comment by lukaszgryglicki** [comment]
Data regenerated, see for example those dashboards:
- [Activity](https://knative.teststats.cncf.io/d/1/activity-repository-groups?orgId=1).
- [Company stats](https://knative.teststats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=d7&var-metric=activity&var-repogroup_name=Knative%20Sandbox&var-companies=All).
They now have 2 repo groups "Knative" and "Knative Sandbox". Same with all other dashboards.

**Comment by xtreme-sameer-vohra** [comment]
Thanks @lukaszgryglicki 
I noticed that the individual repos are gone now from the drop down list. I am assuming I need to update the sql file to get them listed as well now :)

**Comment by lukaszgryglicki** [comment]
One repo can only belong to one repo group, so now you have 2 repo groups, as defined in this file. You can define any set of repos and group them as you like, but you cannot assign the same repo to multiple groups.

**Pull request merged**
