### PR TITLE
vendor: Add

### LINKED ISSUE #98: [go] Add vendor to make it easy to build Docker image
See https://github.com/kubeflow/community/pull/91#discussion_r182616029

Hi, I am a part of Kubeflow and we are trying to dockerize devstats and port it on k8s. I think we could import vendor directory to avoid `go get` in the docker image.

### PR DESCRIPTION
**Pull request by gaocegege**
- Close #98 

PTAL @lukaszgryglicki

### CODE REVIEW

**Comment by gaocegege** [comment]
The first commit is hard to review since it is generated by `dep`, thus I think we could review the latter two PRs.

**Comment by lukaszgryglicki** [comment]
It doesn't work on Go 1.7 (and DevStats worked and compiled from 1.6 to 1.10 so far).
It works for me on 1.10.
How exactly was it generated?
I see some of the go packages listed in INSTALL docs but not all.
On which Go version have you generated this?
I wonder if we generate this on Go 1.7 for instance - will it work on 1.10?
And the opposite: Generate on 1.10 - will o work on 1.7? (I think not - probably this is what happens for me now).

**Comment by dankohn** [comment]
Is there value in supporting versions of Go below 1.10?

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by gaocegege** [comment]
Hi @lukaszgryglicki 

I use https://github.com/golang/dep to generate the vendor directory for this repository, and it only imports the deps in Go code, thus some tools that we used are not imported.

We could do it by write some configs in gopkg.yaml, but I think it is not what we expected. Because the tools that we used are binaries and we should not import them as vendors. Then I think it is better to install them manually.

WDYT?

**Comment by gaocegege** [comment]
I am not sure if it supports Go 1.7, since I have no environment for it. If you think it is necessary, I will take a look. :smile:

**Comment by lukaszgryglicki** [comment]
Ok, so let's focus on Go 1.10 and drop older versions.
I'll merge in minutes, and then I'll have to update all docs - we need to ensure 1.10 is installed in all cases.
More - I'm very wip with supporting auto-deploy from zero (no databases at all) state.
So just give me some time, I need to merge few local branches/server and clean up stuff.

**Comment by lukaszgryglicki** [comment]
Merged, now I need to sync all my local/remote work (3 servers one virtual machine where I use shaphots to test multiple times from zero state).

**Comment by gaocegege** [comment]
Yeah, I can help to update the docs. You could do the high-priority things, thanks for the awesome tool! Hope we could run it on Kubernetes successfully :smile:

**Comment by lukaszgryglicki** [comment]
I need to do it anyway - they're a bit old and now we can use automatic deploy script `devel/deploy_all.sh` to do the job, that is described manually.
I'll do it now while testing on VirtualBox Ubuntu 18.04-beta.2

**Comment by gaocegege** [comment]
OK, cool :smile:

**Pull request merged**
