### PR TITLE
Update Tekton config

### PR DESCRIPTION
**Pull request by afrittoli**
Add the new Tekton owned org tektoncd-catalog.
Set the main repo as tektoncd/pipeline.

Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

Please make sure that you follow instructions from [CONTRIBUTING](https://github.com/cncf/devstats/blob/master/CONTRIBUTING.md)

Specially:
- Check if all tests pass, see [TESTING](https://github.com/cncf/devstats/blob/master/TESTING.md) for deatils.
- Make sure you've added test coverage for new features/metrics.
- Make sure you have updated documentation.
- If you added a new metric, please make sure you have been following instructions about [adding new metric](https://github.com/cncf/devstats/blob/master/METRICS.md).

### CODE REVIEW

**Comment by afrittoli** [comment]
I'm not really sure if this change does what I'm trying to do, I would appreciate a review on it 🙏

**Comment by lukaszgryglicki** [comment]
This change adds a new org, changes the main repo, and adds a new skip path in the golang repo.
Looking good - I'll merge and then update other places where needed.
One caveat - this requires regenerating all dashboards data because the main repo (the one which generates annotations and time ranges) was changed - I can do this full regenerate after my 2 weeks of PTO.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
On it now.

**Comment by lukaszgryglicki** [comment]
Backfilled data for this new org, now regenerating all metrics (including historical/past ones) to include data from the new org.

**Comment by lukaszgryglicki** [comment]
Dashboards data is now generating, needed to add support for cleaning non-UTF8 strings, looks like some of `tektoncd/pipeline` tags had non-utf8 correct names, so needed this fix before I could generate tags for the new version, details here: https://github.com/cncf/devstatscode/commit/6234559fea63090aca9e73828299b162283336f6 and there: https://github.com/cncf/devstatscode/commit/b060e83b9a48fb7f9c7f7bf3310ec7f8ecbcb296

**Comment by lukaszgryglicki** [comment]
This is done.

**Pull request merged**
